// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class AccountOfCourse
{
    public Guid Id { get; set; }

    public Guid? AccountId { get; set; }

    public Guid? CourseId { get; set; }

    public Guid? ClassId { get; set; }

    public int? Status { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual Class Class { get; set; }

    public virtual Course Course { get; set; }

    public virtual EnrollmentStatus StatusNavigation { get; set; }
}