// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class CertificateTemplete
{
    public Guid Id { get; set; }

    public Guid? OrganizationId { get; set; }

    public Guid? CourseId { get; set; }

    public string TemplateName { get; set; }

    public string BackgroundUrl { get; set; }

    public string HtmlTemplate { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual ICollection<Certificate> Certificates { get; set; } = new List<Certificate>();

    public virtual Course Course { get; set; }

    public virtual Organization Organization { get; set; }
}