// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Certificate
{
    public Guid Id { get; set; }

    public Guid? AccountId { get; set; }

    public Guid? CourseId { get; set; }

    public Guid? CertiTempId { get; set; }

    public string CertificateName { get; set; }

    public double? Score { get; set; }

    public Guid? Rank { get; set; }

    public string FileUrl { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual CertificateTemplete CertiTemp { get; set; }

    public virtual Course Course { get; set; }
}