// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ChatHistory
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Role { get; set; }

    public string Message { get; set; }

    public DateTime? Timestamp { get; set; }
}