// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Course
{
    public Guid CourseId { get; set; }

    public Guid WorkspaceId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<LearningGroup> LearningGroups { get; set; } = new List<LearningGroup>();

    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();

    public virtual Workspace Workspace { get; set; }
}