// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Course
{
    public Guid Id { get; set; }

    public Guid CategoryId { get; set; }

    public Guid WorkSpaceId { get; set; }

    public string CourseName { get; set; }

    public string Description { get; set; }

    public double? RatingAverage { get; set; }

    public string ImgUrl { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();

    public virtual WorkSpace WorkSpace { get; set; }
}