// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Lab
{
    public Guid LabId { get; set; }

    public Guid TopicId { get; set; }

    public string Name { get; set; }

    public string Instructions { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Topic Topic { get; set; }
}