// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class LearningGroup
{
    public Guid GroupId { get; set; }

    public Guid CourseId { get; set; }

    public string Name { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}