// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class LessonSubmission
{
    public Guid Id { get; set; }

    public Guid AccountId { get; set; }

    public Guid LessonId { get; set; }

    public DateTime SubmitTime { get; set; }

    public string FileUrl { get; set; }

    public string Note { get; set; }

    public double? TotalScore { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual Lesson Lesson { get; set; }
}