// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Lesson
{
    public Guid Id { get; set; }

    public Guid? TopicId { get; set; }

    public string LessonName { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int? Status { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual ICollection<LessonProgress> LessonProgresses { get; set; } = new List<LessonProgress>();

    public virtual ICollection<Quiz> Quizzes { get; set; } = new List<Quiz>();

    public virtual LessonStatus StatusNavigation { get; set; }

    public virtual Topic Topic { get; set; }
}