// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Method
{
    public Guid Id { get; set; }

    public Guid? ObjectId { get; set; }

    public string MethodName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Object Object { get; set; }

    public virtual ICollection<Script> Scripts { get; set; } = new List<Script>();
}