// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Object
{
    public Guid Id { get; set; }

    public Guid? ScenarioId { get; set; }

    public string ObjectName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual ICollection<Method> Methods { get; set; } = new List<Method>();

    public virtual Scenario Scenario { get; set; }
}