// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Order
{
    public Guid Id { get; set; }

    public Guid? OrganizationId { get; set; }

    public Guid? AccountId { get; set; }

    public Guid? SubcriptionPlanId { get; set; }

    public string Description { get; set; }

    public double? TotalPrice { get; set; }

    public DateTime? OrderTime { get; set; }

    public int? Status { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual OrderStatus StatusNavigation { get; set; }

    public virtual SubscriptionPlan SubcriptionPlan { get; set; }
}