// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Order
{
    public Guid Id { get; set; }

    public Guid? OrganizationId { get; set; }

    public Guid? WorkSpaceId { get; set; }

    public string Description { get; set; }

    public double? TotalPrice { get; set; }

    public DateTime? BookingTime { get; set; }

    public string Status { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual ICollection<Package> Packages { get; set; } = new List<Package>();

    public virtual WorkSpace WorkSpace { get; set; }
}