// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class PackageOfScene
{
    public Guid Id { get; set; }

    public Guid? PackageId { get; set; }

    public Guid? SceneId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Package Package { get; set; }

    public virtual Scene Scene { get; set; }
}