// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Package
{
    public Guid Id { get; set; }

    public Guid? OrderId { get; set; }

    public Guid? WorkSpaceId { get; set; }

    public Guid? PackageTypeId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual ICollection<PackageOfScene> PackageOfScenes { get; set; } = new List<PackageOfScene>();

    public virtual PackageType PackageType { get; set; }

    public virtual WorkSpace WorkSpace { get; set; }
}