// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Package
{
    public Guid PackageId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? MaxMembers { get; set; }

    public int? MaxGroups { get; set; }

    public int? MaxScenes { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Workspace> Workspaces { get; set; } = new List<Workspace>();
}