// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Payment
{
    public Guid Id { get; set; }

    public Guid? OrderId { get; set; }

    public string OrderCode { get; set; }

    public double? Amount { get; set; }

    public string Description { get; set; }

    public string Items { get; set; }

    public string ReturnUrl { get; set; }

    public string CancelUrl { get; set; }

    public string PaymentLink { get; set; }

    public string Status { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Order Order { get; set; }
}