// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Payment
{
    public Guid Id { get; set; }

    public Guid? OrderId { get; set; }

    public string TransactionCode { get; set; }

    public int? Method { get; set; }

    public int? Status { get; set; }

    public double? PaidAmount { get; set; }

    public DateTime? PaidAt { get; set; }

    public virtual PaymentMethod MethodNavigation { get; set; }

    public virtual Order Order { get; set; }

    public virtual PaymentStatus StatusNavigation { get; set; }
}