// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class QuestionSubmission
{
    public Guid Id { get; set; }

    public Guid? QuizSubmissionId { get; set; }

    public Guid? QuestionId { get; set; }

    public Guid? SelectedAnswerId { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Question Question { get; set; }

    public virtual QuizSubmission QuizSubmission { get; set; }

    public virtual Answer SelectedAnswer { get; set; }
}