// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Question
{
    public Guid Id { get; set; }

    public Guid? QuizId { get; set; }

    public int? QuestionType { get; set; }

    public string Description { get; set; }

    public double? Score { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    public virtual ICollection<QuestionSubmission> QuestionSubmissions { get; set; } = new List<QuestionSubmission>();

    public virtual QuestionType QuestionTypeNavigation { get; set; }

    public virtual Quiz Quiz { get; set; }
}