// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Quiz
{
    public Guid Id { get; set; } = Guid.NewGuid();

    public Guid TopicId { get; set; }

    public string QuizName { get; set; }

    public double? Score { get; set; }

    public string Status { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual Topic Topic { get; set; }
}