// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Quiz
{
    public Guid Id { get; set; }

    public Guid? LessonId { get; set; }

    public string QuizName { get; set; }

    public double? TotalScore { get; set; }

    public int? Status { get; set; }

    public bool? IsFinalQuiz { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Lesson Lesson { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual ICollection<QuizSubmission> QuizSubmissions { get; set; } = new List<QuizSubmission>();

    public virtual QuizStatus StatusNavigation { get; set; }
}