// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class QuizSubmission
{
    public Guid Id { get; set; }

    public Guid? AccountId { get; set; }

    public Guid? QuizId { get; set; }

    public DateTime? SubmitTime { get; set; }

    public double? TotalScore { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<QuestionSubmission> QuestionSubmissions { get; set; } = new List<QuestionSubmission>();

    public virtual Quiz Quiz { get; set; }
}