// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class QuizSubmissionAnswer
{
    public Guid Id { get; set; }

    public Guid QuizSubmissionId { get; set; }

    public Guid QuestionId { get; set; }

    public Guid AnswerId { get; set; }

    public virtual Answer Answer { get; set; }

    public virtual Question Question { get; set; }

    public virtual QuizSubmission QuizSubmission { get; set; }
}