// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class QuizSubmission
{
    public Guid Id { get; set; }

    public Guid QuizId { get; set; }

    public Guid AccountId { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public int? ScoreObtained { get; set; }

    public virtual Account Account { get; set; }

    public virtual Quiz Quiz { get; set; }

    public virtual ICollection<QuizSubmissionAnswer> QuizSubmissionAnswers { get; set; } = new List<QuizSubmissionAnswer>();
}