// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Scenario
{
    public Guid Id { get; set; }

    public Guid? SceneId { get; set; }

    public Guid? TopicId { get; set; }

    public string FileUrl { get; set; }

    public string ScenarioName { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual Scene Scene { get; set; }

    public virtual Topic Topic { get; set; }
}