// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Scene
{
    public Guid Id { get; set; }

    public string SceneName { get; set; }

    public string Description { get; set; }

    public string ImgUrl { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual ICollection<PackageOfScene> PackageOfScenes { get; set; } = new List<PackageOfScene>();

    public virtual ICollection<Scenario> Scenarios { get; set; } = new List<Scenario>();

    public virtual ICollection<SceneOfWorkSpace> SceneOfWorkSpaces { get; set; } = new List<SceneOfWorkSpace>();

    public virtual ICollection<Topic> Topics { get; set; } = new List<Topic>();
}