// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class WorkSpace
{
    public Guid Id { get; set; }

    public Guid? OrganizationId { get; set; }

    public string WorkSpaceName { get; set; }

    public int? NumberOfAccount { get; set; }

    public string ImgUrl { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeleteAt { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual ICollection<EnrollmentWorkSpace> EnrollmentWorkSpaces { get; set; } = new List<EnrollmentWorkSpace>();

    public virtual Organization Organization { get; set; }
}