// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Workspace
{
    public Guid WorkspaceId { get; set; }

    public Guid OrganizationId { get; set; }

    public Guid? PackageId { get; set; }

    public string Name { get; set; }

    public bool? IsFree { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();

    public virtual Organization Organization { get; set; }

    public virtual Package Package { get; set; }

    public virtual ICollection<Scene> Scenes { get; set; } = new List<Scene>();
}